### ISSUE TITLE
Crear la vista de reportes estatales, nacionales y mundiales 

### ISSUE THREAD

**Issue by luischang07** [joseocio192/Club-Conquistadores#63]
Generar reportes de
Estadísticas Generales del Club:

- Número total de miembros en el club.
- Distribución por género y edad.
- _Crecimiento o disminución de miembros en los últimos años._ (opcional)

Participación en Actividades:

- Número de clases semanales o mensuales.
- Asistencia promedio a las clases.
- Participación en campamentos, excursiones y eventos especiales.

**Comment by joseocio192** [comment]
nombre es un chingo de chamba te hice una ya las terminas tu las demas👍😌
