### ISSUE TITLE
no hay municipios en canada y estados unidos

### ISSUE THREAD

**Issue by Manuel11238** [joseocio192/Club-Conquistadores#65]
al registrarse, si seleccionas en pais estados unidos o canada, no salen municipios ni ciudad

**Comment by Manuel11238** [comment]
tampoco hay municipios en Baja california, 
no hay ciudad en aguascalientes, asientos.
no hay ciudad en baja california, mexicali,
no hay ciudad en baja california, tijuana,

**Comment by joseocio192** [comment]
Pa q va a haber alla si no hay clubs niño, el @IsaacDavidBeltran no se puso a chambear
